# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute to Firebase"
  lane :distribute do |options|
    UI.message options
    UI.message commit
    if (options[:build_type] === 'test')
      commit = last_git_commit
      hash = commit[:abbreviated_commit_hash]
      branch = git_branch
      android_set_version_name(version_name: "#{hash}-#{branch}")
    elsif (options[:build_name])
      android_set_version_name(version_name: options[:build_name])
    end
    # gradle(task: "clean assembleDebug")
    # firebase_app_distribution(
    #   app: ENV['FIREBASE_PROJECT_ID'],
    #   firebase_cli_token: ENV['FIREBASE_TOKEN'],
    #   android_artifact_type: 'APK'
    # )
  end
end
