name: Build Android App

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'Build'
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      - name: NPM Install
        run: npm ci
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: Distribute to Firebase
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'distribute'
          subdirectory: 'android'
