name: Build Android App

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'Build'
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      - name: NPM Install
        run: npm ci
      - name: Setup Ruby
        run: ruby/setup-ruby@v1
        with: '2.7.6'
      - name: Install Fastlane
        run: cd android && bundle install
      - name: Distribute to Firebase
        run: bundle exec fastlane distribute
