name: Map Input

on:
  workflow_dispatch:
    inputs:
      groups:
        type: choice
        description: Send build to which group?
        required: true
        options:
          - Developers
          - Designers
          - Quality Engineers
          - Accessibility
          - All Groups

env:
  TEST_GROUPS: >
    ${{ fromJson('{
      "Developers": "mobile-devs",
      "Designers": "mobile-designers",
      "Quality Engineers": "mobile-qe",
      "Accessibility": "mobile-a11y",
      "All Groups": "mobile-devs, mobile-designers, mobile-qe, mobile-a11y"
    }')[inputs.groups] }}

jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment and output
        run: |
          echo ${{env.TEST_GROUPS }}
