name: Map Input

on:
  workflow_dispatch:
    inputs:
      groups:
        type: choice
        description: Send build to which group?
        required: true
        options:
          - Developers
          - Designers
          - Quality Engineers
          - Accessibility

env:
  TESTING_GROUPS: >
    ${{ fromJson('{
      "Developers": "mobile-devs",
      "Designers": "mobile-designers",
      "Quality Engineers": "mobile-qe",
      "Accessibility": "mobile-a11y"
    }')[inputs.groups] }}

jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      # - uses: kanga333/variable-mapper@master
      #   id: export
      #   with:
      #     key: '${{ inputs.groups }}'
      #     map: |
      #       {
      #         "Developers": { "groups": "mobile-devs" },
      #         "Designers": { "groups": "mobile-designers" },
      #         "Quality Engineers": { "groups": "mobile-qe" },
      #         "Accessibility": { "groups": "mobile-a11y" }
      #       }
      #     export_to: output
      - name: Echo environment and output
        run: |
          echo ${{env.TESTING_GROUPS }}
