name: Mobile Distribute

on:
  workflow_dispatch:
    inputs:
      build-name:
        required: true
        type: string

jobs:
  build-android-app:
    uses: ./.github/workflows/build-android-app.yml
    with:
      build-name: ${{ github.event.inputs.build-name }}
    secrets: inherit
