name: Build Android App

on:
  workflow_call:
    inputs:
      build-name:
        type: string
      build-type:
        type: string
      test-groups:
        type: string
  workflow_dispatch:
    inputs:
      build-name:
        required: true
        type: string
        description: Build Name
      test-groups:
        type: choice
        description: Send build to which group?
        required: true
        options:
          - Developers
          - Designers
          - Quality Engineers
          - Accessibility
          - All Groups

env:
  TEST_GROUPS: >
    ${{ fromJson('{
      "Developers": "mobile-devs",
      "Designers": "mobile-designers",
      "Quality Engineers": "mobile-qe",
      "Accessibility": "mobile-a11y",
      "All Groups": "mobile-devs, mobile-designers, mobile-qe, mobile-a11y"
    }')[inputs.test-groups] }}

jobs:
  build-android:
    name: Build Android App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      - name: NPM Install
        run: npm ci
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'android'
      - name: Distribute to Firebase
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'distribute'
          subdirectory: 'android'
          options: '{ "build_name": "${{ inputs.build-name }}", "build_type": "${{ inputs.build-type }}", "hash": "${{ github.event.pull_request.head.sha }}", "branch": "${{ github.event.pull_request.head.ref }}", "test_groups": "${{ env.TEST_GROUPS }}" }'
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
