name: Deploy Mobile App Release

on:
  workflow_dispatch:
  push:
    branches: [release/*]
    # paths: []

jobs:
  prerelease:
    name: Create Release build
    uses: ./.github/workflows/mobile-app-build.yml
    with:
      build-type: prerelease
      test-groups: Devs & QE
    secrets: inherit
