name: Labeled Mobile PR

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'Ready for A11y' || github.event.label.name == 'Ready for QE'
    name: Build From Latest PR Commit
    uses: ./.github/workflows/mobile-app-build.yml
    with:
      build-name: ${{ null }}
      build-type: 'test'
      test-groups: ${{ github.event.label.name == 'Ready for A11y' && 'mobile-ally' || 'mobile-qe' }}
    secrets: inherit
