name: Build Android App

on:
  workflow_call:
    inputs:
      build-name:
        type: string
      build-type:
        type: string
  workflow_dispatch:
    inputs:
      build-name:
        required: true
        type: string
  # pull_request:
  #   types: [labeled]

jobs:
  build-android:
    # if: github.event.label.name == 'Build'
    name: Build Android App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      - name: NPM Install
        run: npm ci
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'android'
      - name: Distribute to Firebase
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'distribute'
          subdirectory: 'android'
          options: '{ "build_name": "${{ inputs.build-name }}", "build_type":  "${{ inputs.build-type }}"}'
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
