name: Deploy Mobile App Release

on:
  workflow_dispatch:
  push:
    branches: [releases/*]
    # paths: []

jobs:
  name: Create Release build
  uses: ./.github/workflows/mobile-app-build.yml
  with:
    build-type: 'prerelease'
  secrets: inherit
