name: Build iOS and Android Apps

on:
  workflow_call:
    inputs:
      build-name:
        type: string
      build-type:
        type: string
  workflow_dispatch:
    inputs:
      build-name:
        required: true
        type: string

jobs:
  build-android-app:
    name: Build Android App
    uses: ./.github/workflows/mobile-app-android-build.yml
    with:
      build-name: ${{ github.event.inputs.build-name }}
      build-type: ${{ github.event.inputs.build-type || 'manual' }}
    secrets: inherit
  build-ios-app:
    name: Build iOS App
    uses: ./.github/workflows/mobile-app-ios-build.yml
    with:
      build-name: ${{ github.event.inputs.build-name }}
    secrets: inherit
